name: Build Jekyll

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-push:
    if: contains(github.event.head_commit.message, '[run-ci]')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Build site
        run: bundle exec jekyll build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages
